### ISSUE TITLE
Please add credit to `kmp-viewmodel`

### ISSUE THREAD

**Issue by hoc081098** [getspherelabs/meteor-kmp#31]
Hi, I have noticed some code in `meteor-viewmodel` is similar to my library `kmp-viewmodel`(https://github.com/hoc081098/kmp-viewmodel/tree/master/viewmodel).
Could you please add credits/links to my library?
Thanks 🙏

**Comment by hoangchungk53qx1** [comment]
I noticed the same thing ! .

**Comment by buiduclam09** [comment]
I noticed the same thing ! .

**Comment by dungngminh** [comment]
Same to me. I noticed the same thing !. Please leave the credit

**Comment by olololoe110399** [comment]
Please leave the credit

**Comment by hoc081098** [comment]
🙏

**Comment by behzodhalil** [comment]
Hey, @hoc081098 

Thanks for your attention! Sure, I'll added your your library as credit :)

In the future, I'll change `meteor-viewmodel` code. 

@hoangchungk53qx1 @olololoe110399 @dungngminh @olololoe110399 Thank you all very much for your attention!
